{% set version = "3.0.0b3" %}
{% set version_str = "v3.0.0-beta-3" %}

package:
    name: protobuf
    version: {{ version }}

source:
    fn: protobuf_{{ version }}.tar.gz
    url: https://github.com/google/protobuf/archive/{{ version_str }}/protobuf-{{ version_str }}.tar.gz
    md5: 89afd3855f2d4782e59c09e07d9efa67

build:
    number: 0
    features:
        - vc9                # [win and py27]
        - vc10               # [win and py34]
        - vc14               # [win and py35]

requirements:
    build:
        - git
        - cmake              # [win]
        - autoconf           # [unix]
        - automake           # [unix]
        - libtool            # [unix]
        - pkg-config         # [unix]
        - gcc                # [linux]
        - zlib
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]

    run:
        - libgcc             # [linux]
        - zlib
        - python
        - six
        - ordereddict        # [py26]
        - unittest2          # [py26]

test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
        - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
        - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]

    imports:
        - google
        - google.protobuf
        - google.protobuf.internal
        - google.protobuf.pyext

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: Protocol Buffers - Google's data interchange format

extra:
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - jjhelmus
        - ocefpaf
